name: haskell-unit-generated
version: 0.1.0.0
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
#  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: https://github.com/an-death/haskell-unit-generated

dependencies:
- base >= 4.7 && < 5
- aeson >=1.0 && <2.0
- base64-bytestring >1.0 && <2.0
- bytestring >=0.10.0 && <0.11
- case-insensitive
- containers >=0.5.0.0 && <0.8
- deepseq >= 1.4 && <1.6
- exceptions >= 0.4
- http-api-data >= 0.3.4 && <0.5
- http-client >=0.5 && <0.7
- http-client-tls
- http-media >= 0.4 && < 0.9
- http-types >=0.8 && <0.13
- iso8601-time
- microlens >= 0.4.3 && <0.5
- mtl >=2.2.1
- network >=2.6.2 && <3.9
- random >=1.1
- safe-exceptions <0.2
- text >=0.11 && <1.3
- time >=1.5
- transformers >=0.4.0.0
- unordered-containers
- vector >=0.10.9 && <0.13
- haskell-client-generated
- openapi3
- aeson-deriving
- lens
- generic-lens

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror=missing-fields
  - -Werror=incomplete-record-updates
  - -Werror=missing-methods
  - -Werror=incomplete-patterns
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Widentities
  - -Wredundant-constraints
  - -funbox-strict-fields

default-extensions:
  - RecordWildCards
  - NamedFieldPuns
  - DuplicateRecordFields
  - OverloadedLabels
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances
  - StandaloneDeriving
  - ScopedTypeVariables
  - ExplicitForAll
  - TypeOperators
  - TypeApplications
  - DeriveGeneric
  - MonoLocalBinds
  - DerivingStrategies
  - BlockArguments
  - PostfixOperators
  - TupleSections
  - LambdaCase
  - NumericUnderscores
  - MultiWayIf
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DerivingVia
  - EmptyDataDecls
  - ExistentialQuantification
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - NumDecimals
  - PatternSynonyms
  - RankNTypes
  - TypeFamilies
  - ViewPatterns
  - PartialTypeSignatures

library:
  source-dirs: lib
tests:
  haskell-unit-generated-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wno-incomplete-uni-patterns
    dependencies:
      - haskell-unit-generated
      - hspec
      - hspec-core
      - hspec-expectations-json
      - aeson-qq

