resolver: lts-18.10
build:
  haddock-arguments:
    haddock-args:
    - "--odir=./docs"
packages:
  - '.'

extra-deps:
  - git: https://github.com/fintech-development/haskell-client-generated.git
    commit: 94bcd90f651175381221bd175b2d2007283bf261
  - aeson-deriving-0.1.1.2

